spring.jmx.enabled=false
spring.main.lazy-initialization=true
server.port=80
gemini.api.key=${GEMINI_API_KEY:}
spring.mvc.throw-exception-if-no-handler-found=true

# Give the app enough time to start on Azure (default is too short)
server.tomcat.connection-timeout=60000

# Reduce startup time
spring.main.banner-mode=off
logging.level.root=WARN
logging.level.com.todo=INFO
