import java.time.LocalDate; // Import the date tool

public class Task {
    // 1. Private Fields (Encapsulation)
    private String title;
    private String description;
    private boolean isCompleted;
    private LocalDate dueDate; // Added date

    // 2. Constructor
    public Task(String title, String description, LocalDate dueDate) {
        this.title = title;
        this.description = description;
        this.dueDate = dueDate;
        this.isCompleted = false; // Default to false when created
    }

    // 3. Getters and Setters (Generated by IntelliJ)
    public String getTitle() { return title; }
    public void setTitle(String title) { this.title = title; }

    public String getDescription() { return description; }
    public void setDescription(String description) { this.description = description; }

    public boolean isCompleted() { return isCompleted; }
    public void setCompleted(boolean completed) { isCompleted = completed; }

    public LocalDate getDueDate() { return dueDate; }
    public void setDueDate(LocalDate dueDate) { this.dueDate = dueDate; }

    // 4. The toString Override
    // This makes printing the task look nice in the console
    @Override
    public String toString() {
        // Uses a "Ternary Operator" to print [X] if done, [ ] if not
        String checkbox = isCompleted ? "[X]" : "[ ]";
        return checkbox + " " + title + " (Due: " + dueDate + ")";
    }
    // Converts the task into a String format for the file:
// Format: Title|Description|Date|IsCompleted
    public String toFileFormat() {
        return title + "|" + description + "|" + dueDate + "|" + isCompleted;
    }
}